frase = ('Curso em vídeo python')
print(frase[:14])
print(frase.count('o'))
print(frase.find('deo'))
print('Curso' in frase)
print(frase.replace('python', 'android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase = ('   Aprenda python  ')
print(frase)
print(frase.strip())
print(frase.lstrip())
print(frase.rstrip())
frase = ('Curso em vídeo python')
print(frase.split())
print(''.join(frase))